from tkinter import*
a=Tk()
def clr():
    e.delete(0,END)
    e1.delete(0,END)
    e2.delete(0,END)
def total():
    t=int(e.get())+int(e1.get())
    e2.insert(0,t)
def sub():
    s=int(e.get())-int(e1.get())
    e2.insert(0,s)
def mul():
    m=int(e.get())*int(e1.get())
    e2.insert(0,m)
def div():
    d=int(e.get())/int(e1.get())
    e2.insert(0,d)
a.title("welcome")
a.geometry("500x500")
a.config(bg="green")
l=Label(a,text="calculator")
l.pack(pady=20)
l1=Label(a,text="num1")
l1.pack(pady=20)
e=Entry()
e.pack()
l2=Label(a,text="num2")
l2.pack(pady=20)
e1=Entry()
e1.pack()
e2=Entry()
e2.pack(pady=10)
b=Button(a,text="add",command=total)
b.pack()
b1=Button(a,text="sub",command=sub)
b1.pack()
b2=Button(a,text="multiple",command=mul)
b2.pack()
b3=Button(a,text="division",command=div)
b3.pack()
b4=Button(a,text="clear",command=clr)
b4.pack(pady=10)
