from tkinter import*
a=Tk()
def clr():
    e.delete(0,END)
    e1.delete(0,END)
    e2.delete(0,END)
    e3.delete(0,END)
    e4.delete(0,END)
    e5.delete(0,END)
    e6.delete(0,END)
def total():
    t=int(e.get())+int(e1.get())+int(e2.get())+int(e3.get())+int(e4.get())+int(e5.get())
    e6.insert(0,t)
def cutoff():
    c=int(e2.get())+int(e3.get())/2+int(e4.get())/2
    e7.delete(0,END)
    e7.insert(0,c)
a.title("progress report")
a.geometry("1500x1500")
a.config(bg="yellow")
l=Label(a,text="mark list")
l.pack(pady=20)
l1=Label(a,text="tam")
l1.pack(pady=20)
e=Entry()
e.pack()
l2=Label(a,text="eng")
l2.pack(pady=20)
e1=Entry()
e1.pack()
'''e2=Entry()
e2.pack(pady=10)'''
l3=Label(a,text="mat")
l3.pack(pady=20)
e2=Entry()
e2.pack()
l4=Label(a,text="phy")
l4.pack(pady=20)
e3=Entry()
e3.pack()
l5=Label(a,text="che")
l5.pack(pady=20)
e4=Entry()
e4.pack()
l6=Label(a,text="cs")
l6.pack(pady=20)
e5=Entry()
e5.pack()
e6=Entry()
e6.pack(pady=10)
b=Button(a,text="add",command=total)
b.pack()
b1=Button(a,text="cut off",command=cutoff)
b1.pack()
e7=Entry()
e7.pack()
b2=Button(a,text="clear",command=clr)
b2.pack(pady=10)

